### PR TITLE
Replace PNG diagrams with PlantUML

### PR DESCRIPTION
**Pull request by N-Nagorny**

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]
LGTM 👏 

The side-by-side (new is on the left)

image

**Comment by garethsb** [comment]
Are we OK to use live rendered images? Will the spec rendering scripts have to save as PNG or SVG or something? @peterbrightwell

**Review by prince-chrismc — APPROVED** [review]
Nice solution!

**Comment by N-Nagorny** [comment]
Hi, @peterbrightwell.
I extracted rendering PlantUML to a separate workflow as we discussed on the call. Is this approach with a pushing bot acceptable?

**Comment by prince-chrismc** [comment]
I like this approach because

* you only need to edit the files locally and they will always be updated in your branch
* it's SVG which is much better for tracking in git

The challenge is a push to main/1.0-dev might be two commits. Which is acceptable that it will always be kept in sync

Looking into this action it only runs if you edit or add the PlantUML files https://github.com/grassedge/generate-plantuml-action/blob/7795d4ecf0934e3e52cb1244f8ca2e9869939cf8/src/main.ts#L39-L41... So changes to the RAML would not make a new commit.

**Pull request merged**
